name: Process Code with Gemini

on:
  push:
    branches:
      - main  # Change to your main branch if needed

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use your required Node.js version

      - name: Install Dependencies
        run: npm install  # Run this if you have any dependencies (adjust accordingly)

      - name: Process Code with Gemini Logic
        run: |
          # Replace 'inputFile.js' and 'outputFile.js' with your actual file names
          node geminiLogic.js path/to/your/code/inputFile.js path/to/processed/code/outputFile.js

      - name: Create a new branch and push changes
        run: |
          # Get the current commit hash
          GIT_COMMIT_HASH=$(git rev-parse HEAD)
          # Create a new branch name
          NEW_BRANCH="processed-code-${GIT_COMMIT_HASH}"
          git checkout -b $NEW_BRANCH
          # Add the processed file to the new branch
          git add path/to/processed/code/outputFile.js  # Update this based on your output
          git commit -m "Add processed code from Gemini"
          git push origin $NEW_BRANCH
